### ISSUE TITLE
Holy crap, HTTP500 al subir un inventario

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#102]
**2014-09-10T02:06:02.658190+00:00 heroku[router]:** at=info method=GET path="/inventarios" host=adela.datos.gob.mx request_id=73001edc-8b18-4127-aa30-c7bd367d40af fwd="148.243.219.246" dyno=web.1 connect=1ms service=9184ms status=200 bytes=2122
**2014-09-10T02:06:02.847180+00:00 heroku[router]:** at=info method=GET path="/assets/file-08562d01694bd7b93b2d5668b322aa65.png" host=adela.datos.gob.mx request_id=774079f6-c5c1-457d-ad17-4c7f9e2dbdcb fwd="148.243.219.246" dyno=web.1 connect=1ms service=8ms status=200 bytes=482
**2014-09-10T02:06:02.837491+00:00 heroku[router]:** at=info method=GET path="/assets/download-4a6ed7113c8c7871d01425a80998598b.png" host=adela.datos.gob.mx request_id=5eb7adbc-4c63-40a0-a164-5f2d527e30fd fwd="148.243.219.246" dyno=web.1 connect=3ms service=4ms status=200 bytes=486
**2014-09-10T02:06:02.857675+00:00 heroku[router]:** at=info method=GET path="/assets/application-756203c748b43c406c3bd636c611724c.css" host=adela.datos.gob.mx request_id=497e017f-eb96-4cbd-ae17-6cfb5652399b fwd="148.243.219.246" dyno=web.1 connect=2ms service=16ms status=200 bytes=489
**2014-09-10T02:06:06.328302+00:00 heroku[router]:** at=info method=GET path="/inventarios/new?new_version=true" host=adela.datos.gob.mx request_id=4f4ac7f8-80b6-448d-ae6e-ed45adca7137 fwd="148.243.219.246" dyno=web.1 connect=2ms service=217ms status=200 bytes=2122
**2014-09-10T02:06:38.835983+00:00 heroku[router]:** at=error code=H13 desc="Connection closed without response" method=POST path="/inventarios" host=adela.datos.gob.mx request_id=ace74b4f-91f5-44cf-9271-88b6aee1741b fwd="148.243.219.246" dyno=web.1 connect=1ms service=15982ms status=503 bytes=1085455
**2014-09-10T02:06:38.808500+00:00 app[web.1]:** E, [2014-09-10T02:06:38.808351 #2] ERROR -- : worker=0 PID:128 timeout (16s > 15s), killing
**2014-09-10T02:06:38.874023+00:00 app[web.1]:** I, [2014-09-10T02:06:38.873687 #143]  INFO -- : worker=0 ready
**2014-09-10T02:06:38.839778+00:00 app[web.1]:** E, [2014-09-10T02:06:38.839660 #2] ERROR -- : reaped #<Process::Status: pid 128 SIGKILL (signal 9)> worker=0
**2014-09-10T02:07:06.717073+00:00 heroku[router]:** at=info method=GET path="/sedesol/catalogo.json" host=adela.datos.gob.mx request_id=031e95fe-ddc7-4aac-a694-3766f00a4407 fwd="189.202.202.129" dyno=web.1 connect=1ms service=3179ms status=200 bytes=1495
^C
 !    Command cancelled.

**Comment by carlosmaya** [comment]
outdated
