### ISSUE TITLE
Agregar campo para landingPage

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#147]

**Comment by rodowi** [comment]
dcat:LandingPage debe ser poblado por el campo dataDictionary de los CSVS

**Comment by carlosmaya** [comment]
@rodowi dataDictionary será mandatorio? o Adela solamente va a checar el formato ( URL ) en caso de que venga en el CSV?

**Comment by rodowi** [comment]
si siguen el formato v2 viene dataDictionary como opcional
si siguen el formato v3 viene landingPage como obligatorio

**Comment by rodowi** [comment]
NECESITAMOS BACKWARD COMPATIBILITY
