### ISSUE TITLE
Como Administrador de Datos de una Organización puedo subir el inventario de datos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#266]

**Comment by rodowi** [comment]
Aún falta rebotarlo con el taskforce

**Comment by carlosmaya** [comment]
Validaciones que se aplican

- [ ] El campo `fecha estimada de publicación` ( Columna H ) debe estar en el formato AAAA-MM
- [ ] Los recursos de un mismo conjunto de datos deben tener la misma `fecha estimada de publicación`
- [ ] Validar que se describan todos los recursos del mismo conjunto agrupados.
- [ ] Cuando el valor del dato `¿Tiene datos privados?` ( columna E ) sea distinto a *Público* entonces la columna F no puede estar vacía o nula.

**Comment by carlosmaya** [comment]
closed by #374
