### ISSUE TITLE
Agregar funcionalidad para designar a los Administradores y Enlaces de cada Organización

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#289]

**Comment by rodowi** [comment]
@carlosmaya  ¿diferenciar de qué?

**Comment by carlosmaya** [comment]
Los usuarios de una Organización pueden ser del tipo:

- [ ] Administrador  ( solamente se permite uno por organización )
- [ ] Enlace  ( solamente se permite uno por organización )
- [ ] Funcionario ( puede haber varios )
