### ISSUE TITLE
agregar checkboxes para seleccionar los conjuntos a incluir en plan de apertura

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#337]
<img width="869" alt="screen shot 2015-09-07 at 11 52 01 am" src="https://cloud.githubusercontent.com/assets/705860/9720747/dfe40fee-5556-11e5-8df0-424b0b0c4226.png">

**Comment by rodowi** [comment]
en esta linea es donde se genera el plan a partir del inventario:
https://github.com/mxabierto/adela/blob/development/app/controllers/opening_plan_controller.rb#L7

**Comment by rodowi** [comment]
Lo mejor es que todo lo que se cargue en el inventario se vea en la pantalla de Plan de Apertura, y que sea en esta pantalla (plan) donde se seleccionen con checkboxes http://localhost:3000/opening_plan/new

**Comment by rodowi** [comment]
La forma:
https://github.com/mxabierto/adela/blob/development/app/views/opening_plan/new.html.haml#L16

El controlador:
https://github.com/mxabierto/adela/blob/development/app/controllers/opening_plan_controller.rb#L13

**Comment by carlosmaya** [comment]
closed by #361
