### ISSUE TITLE
Incluir en el home de la dependencia el resumen del catálogo publicado

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#339]
![adela-339](https://cloud.githubusercontent.com/assets/2633527/10519667/4a8ef258-732c-11e5-9154-e78f3add8b9f.png)

**Comment by jimenezjrs** [comment]
Le hice un pequeño tweak a los estilos que se muestran ahí para diferenciar. Si no les agrada me dicen :).

**Comment by jimenezjrs** [comment]
![screen shot 2015-10-15 at 11 56 51 am](https://cloud.githubusercontent.com/assets/633095/10521181/f4f88c16-7333-11e5-8edf-8291e793001e.png)
