### ISSUE TITLE
No hay manera de hacer un update al plan de apertura

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#355]
La operación de new siempre parte de lo que lee del inventario, pero no de un plan de apertura previo

**Comment by carlosmaya** [comment]
La funcionalidad para actualizar el plan será la siguiente:

*Se mostrarán los registros del inventario en la pantalla del plan de apertura; y con el plan de apertura actual se llenan los campos de descripción, frecuencia y fecha de publicación de aquellos que hacen match en título con el inventario*

**Comment by carlosmaya** [comment]
closed by #357
