### ISSUE TITLE
Después de subir un inventario deberían indicarme qué sigue

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#360]
Podemos dejar un mensaje "Se cargó el inventario con éxito, ahora genera el plan de apertura blah blah blah"

**Comment by carlosmaya** [comment]
ahorita se muestra un botón

![screen shot 2015-09-08 at 6 33 12 pm](https://cloud.githubusercontent.com/assets/2633527/9750024/37435e1e-5658-11e5-989c-ca4614027535.png)

**Comment by rodowi** [comment]
yo no lo veo en staging

<img width="862" alt="screen shot 2015-09-09 at 10 21 55 am" src="https://cloud.githubusercontent.com/assets/705860/9766023/9fcd4b32-56dc-11e5-8df9-1068652d1160.png">

**Comment by carlosmaya** [comment]
ya está el PR #366

**Comment by carlosmaya** [comment]
closed by #366
