### ISSUE TITLE
Al descargar el plan de apertura, veo que faltan otros campos

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#363]
<img width="911" alt="screen shot 2015-09-08 at 3 57 53 pm" src="https://cloud.githubusercontent.com/assets/705860/9747278/6c150ffe-5642-11e5-892c-13b2fc85379f.png">

**Comment by carlosmaya** [comment]
este depende del #289 porque actualmente no se sabe quienes son los contactos de cada Institución
