### ISSUE TITLE
Embedded spreadsheet

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#45]
Constantemente se suben hojas con codificaciones no estándar.

Se volverá problemática la carga, ya que a los usuarios no se les hace entender que su codificación está mal.

Por otra parte, es complicado también explicarles que work flow tener para evitar estos problemas.

La solución para todo esto es que lo llenen online

**Comment by carlosmaya** [comment]
se resolverá con la funcionalidad para generar el catálogo desde Adela
