### ISSUE TITLE
La liga al inventario plantilla está mal

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#46]
Necesitamos cambiar la liga al inventario plantilla, ya que es una versión vieja, ASCII y con esquema malo.

https://s3-ap-southeast-1.amazonaws.com/adela-staging/template/plantilla_de_inventario.csv

**Comment by rodowi** [comment]
Lo más fácil sería hacer que la descarga no sea de AWS sino directamente del link bit.y/inventario-de-datos-v2

Por si hay cambios al inventario

**Comment by carlosmaya** [comment]
las plantillas están dentro mxabierto/guia
