### ISSUE TITLE
Al entrar a Catálogo se valida que la Organización tenga Inventario y Plan de Apertura

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#464]

**Comment by carlosmaya** [comment]
- [ ] Al entrar por primera vez en la sección de `Catálogo de Datos` se debe mostrar la pantalla con el checklist. 
- [ ] Una vez que el haga `checked` en todas las opciones se debe habilitar el botón de `Continuar`
- [ ] La pantalla solamente se presentará una vez y se guardará registro por Organización de que se Aceptó el checklist

![screen shot 2015-10-01 at 1 28 23 pm](https://cloud.githubusercontent.com/assets/2633527/10229951/5117eb44-6840-11e5-8023-6cee24ca6668.png)

**Comment by rodowi** [comment]
Ya no será un checklist si no un mensaje de que regreses a Plan de Apertura o Inventario en caso de que te falte alguno de esos
