### ISSUE TITLE
En Catálogo: Tooltips sobre los campos del conjunto

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#470]
Algunos se llenan en el Plan de Apertura, y otros en el Inventario

**Comment by carlosmaya** [comment]
Los textos a usar son la `Descripción` + `Ejemplo` del [spreadsheet](https://docs.google.com/a/opi.la/spreadsheets/d/14J3gCm5ERGYtN_p2KiXK5ttr8Eh9dapL-tSVbeFC2pM/edit?usp=sharing)

![screen_shot_2016-05-03_at_14_52_58](https://cloud.githubusercontent.com/assets/2633527/14996573/3c3d053e-1140-11e6-8205-6e7381c50c38.png)
