### ISSUE TITLE
Editar la información del conjunto de datos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#503]
depende del #455 y #468

**Comment by rodowi** [comment]
La información es prellenada pero se puede editar.

Los campos editables van justo arriba de la tabla de recursos

**Comment by rodowi** [comment]
como se ve en #502

**Comment by carlosmaya** [comment]
** Mock de la pantalla **

![1_editar_conjunto](https://cloud.githubusercontent.com/assets/2633527/10376915/0affe7ca-6dc6-11e5-8f11-5970c2368c73.png)
