### ISSUE TITLE
Marcar en rojo los campos obligatorios que faltan por llenar

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#551]

**Comment by rodowi** [comment]
@carlosmaya en qué pantallas?

**Comment by rodowi** [comment]
displaying-validation-errors-in-views

**Comment by carlosmaya** [comment]
**Pantalla de edición de datos del conjunto**

![adela-1-551](https://cloud.githubusercontent.com/assets/2633527/10562318/8d29d1b8-751c-11e5-9ec3-f0ed8e93fade.png)

**Pantalla de edición de datos del recurso**

![adela-2-551](https://cloud.githubusercontent.com/assets/2633527/10562319/9a69cbb2-751c-11e5-8d8e-f401e11e225a.png)
