### ISSUE TITLE
Agregar un mensaje para invitar a documentar los recursos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#552]
"Continua con la documentación de los recursos"

**Comment by rodowi** [comment]
![screen shot 2015-10-17 at 7 19 28 pm](https://cloud.githubusercontent.com/assets/705860/10561870/03a691dc-7504-11e5-8fcc-bb258411764d.png)

**Comment by rodowi** [comment]
![screen shot 2015-10-17 at 7 33 43 pm](https://cloud.githubusercontent.com/assets/705860/10561906/023e2d1c-7506-11e5-9519-7135a17e3f88.png)

**Comment by carlosmaya** [comment]
closed by #569
