### ISSUE TITLE
Dejar en blanco los campos del recurso  Período de tiempo cubierto ( inicio y fin )

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#553]

**Comment by rodowi** [comment]
te refieres a que no sean obligatorios?

**Comment by carlosmaya** [comment]
Se están prellenando con valores que vienen del inventario, pero en algunos casos no son fechas completas y solamente se pone el año en el inicio, en tales casos es mejor dejarlos en blanco y obligar al que el funcionario indique las fechas de inicio y fin

![adela-553](https://cloud.githubusercontent.com/assets/2633527/10562303/ff22b560-751b-11e5-8249-d58fcfcb31d9.png)

**Comment by carlosmaya** [comment]
no vienen del Inventario, pero está apareciendo un valor de 2015 que puede ser confuso, mejor dejarlo en blanco

**Comment by rodowi** [comment]
no lo he podido replicar, pero no lo deberíamos de forzar en blanco porque puede que tengas ya un valor guardado

**Comment by carlosmaya** [comment]
No se ha podido replicar
