### ISSUE TITLE
En pantalla para editar los datos del conjunto se debe indicar al funcionar cuando ya pueda publicar

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#555]
Sugerencia: 

- Agregar botón de Siguiente ( debe estar inhabilitado por default y se debe activar en cuanto el funcionario haya llenado correctamente la información del conjunto y por lo menos 1 recurso para publicar )
- Debe de llevarlo al siguiente conjunto en la lista

**Comment by rodowi** [comment]
http://jqueryvalidation.org/valid

**Comment by rodowi** [comment]
no es necesario validar la forma, el next sólo te manda al sig. dataset

**Comment by carlosmaya** [comment]
closed by #599
