### ISSUE TITLE
Como funcionario también puedo seleccionar los recursos ya Publicados

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#579]
![adela-579](https://cloud.githubusercontent.com/assets/2633527/10581497/a2f62302-7648-11e5-99a9-a9cca2fb6e73.png)

**Comment by rodowi** [comment]
y después de "despublicar" ¿qué pasa? ¿se actualiza la máquina de estados a "Listo para publicar"? @babasbot

NOTA: esto es más complicado que simplemente agregar checkboxes

**Comment by carlosmaya** [comment]
se incluyó dentro de #605
