### ISSUE TITLE
Si no se ha Generado el Plan de Apertura debo ver un mensaje diciendo que me hacen falta completar el paso 2

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#585]
## Precondiciones

1. Haber subido el Inventario de Datos (  se puede usar el archivo spec/fixtures/files/inventario_general_de_datos.xlsx )
2. NO 

## Caso de prueba

1. Validar mensaje diciendo que hace falta el paso 2  ( Ir al menú `Catálogo de Datos` )
![screen shot 2015-10-19 at 2 38 43 pm](https://cloud.githubusercontent.com/assets/2633527/10589126/23230cb8-766f-11e5-8b71-f2e682d0b519.png)

2. El link de `Plan de Apertura` debe apuntar a `opening_plan#index`

**Comment by abisosa** [comment]
@camara este lo hice sin querer en el  PR del 584 pero no se como hacer que waffle agarre ambos 'closes'

**Comment by carlosmaya** [comment]
según yo, hay que agregar `closes ` por cada issue, algo así

```
closes #584
closes #585
```
