### ISSUE TITLE
Como funcionario debo ver un conjunto para el Inventario de Datos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#586]
## Precondiciones

1. Haber subido el Inventario de Datos
2. Haber generado el Plan de Apertura

## Caso de prueba

1. Ir a opción de menú `Catálogo de Datos`
2. Validar que se muestre el conjunto y recurso creado para el Inventario de Datos
3. Para el Conjunto validar que en `Recursos documentados` este `1 de  1`
4. Para el Conjunto validar que en `Fecha de compromiso` este `28-Ago-2015`
5. Para el Recurso validar que aparezca un checkbox con `checked=true`
6. Para el Recurso validar que en `Estatus de publicación` este `Listo para publicar`
7. Para el Recurso validar que en `Acciones` este `Actualizar`

![adela-586](https://cloud.githubusercontent.com/assets/2633527/10589513/508d509e-7671-11e5-9595-46781faf1d4b.png)

**Comment by abisosa** [comment]
@camara en este escenario la funcionalidad hace que marque '0 de 1' en recursos documentados y la acción de 'Actualizar' no existe. Aparte de hacer la prueba corrijo el código para que tenga el link de 'Actualizar' y contabilice los recursos?

**Comment by abisosa** [comment]
@camara para probar este caso sigue sirviendo el archivo que se encuentra en fixtures: 'inventario_general_de_datos.xlsx' ?
