### ISSUE TITLE
En Catálogo, el funcionario debe ver la lista de conjuntos marcados como Público en el Inventario

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#588]
## Precondiciones

1. Haber subido el Inventario de Datos
2. Haber generado el Plan de Apertura

## Caso de prueba

1. Ir a opción de menú `Catálogo de Datos`
2. Validar que se muestren los conjuntos marcados como `Público` en el Inventario

**Comment by rodowi** [comment]
En otros issues debería ir:

**Pantalla del Plan de Apertura donde se muestran los conjuntos y sus fechas de publicación**

![adela-588b](https://cloud.githubusercontent.com/assets/2633527/10590148/cf3e9382-7674-11e5-8bd3-f27dd0f4f657.png)

3. Para el Conjunto validar que en `Recursos documentados` este `0 de N` ( N = es el total de recursos que se incluyeron en el Inventario )
4. Para el Conjunto validar que en `Fecha compromiso` este la fecha que aparece en el Plan de Apertura para el conjunto
5. Para los Recursos validar que NO se muestre ningún checkbox
6. Para los Recursos validar que en `Estatus de publicación` este `Falta información`
7. Para los Recursos validar que en `Acciones` este `Completar`

![adela-588](https://cloud.githubusercontent.com/assets/2633527/10590059/55e3f518-7674-11e5-9102-be9a45d866e4.png)

@carlosmaya
