### ISSUE TITLE
Si el dataset no tiene título, truena la publicación

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#595]
Simplemente llegué al catálogo, entré y edité un recurso, y quise publicar

<img width="619" alt="screen shot 2015-10-19 at 9 54 26 pm" src="https://cloud.githubusercontent.com/assets/705860/10596645/ff54028c-76ab-11e5-96f5-ae7ee29b22c5.png">

**Comment by carlosmaya** [comment]
relacionado a #617
