### ISSUE TITLE
Cuando se actualiza el inventario se deben actualizar los metadatos del dataset

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#646]
* Fecha de última actualización
* URL de descarga
* Frecuencia de actualización

**Comment by rodowi** [comment]
similar https://github.com/mxabierto/adela/pull/670

**Comment by carlosmaya** [comment]
* en `datasets#edit` se puede ver Frecuencia de Actualización
* en `distributions#edit` están la URL de descarga y la Fecha de última modificación de datos

**Comment by abisosa** [comment]
@carlosmaya creo que la fecha de última modificación sí la prueba lo que hizo @rodowi en el #670
