### ISSUE TITLE
Cuando se actualiza el plan de apertura no se deben duplicar los conjuntos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#659]

**Comment by rodowi** [comment]
![screen shot 2015-10-26 at 8 49 11 am](https://cloud.githubusercontent.com/assets/705860/10732214/a0973698-7bbe-11e5-9c01-9810316b99fb.png)

**Comment by rodowi** [comment]
<img width="864" alt="screen shot 2015-10-26 at 10 28 16 am" src="https://cloud.githubusercontent.com/assets/705860/10735219/98e1dd6e-7bcc-11e5-85df-bd484e008b68.png">
