### ISSUE TITLE
En catálogo los datasets deben tener fecha dde compromiso fijada en el plan

### ISSUE THREAD

**Issue by rodowi** [mxabierto/adela#675]
- [ ] Para el Conjunto validar que en Fecha compromiso este la fecha que aparece en el Plan de Apertura para el conjunto

**Pantalla del Plan de Apertura donde se muestran los conjuntos y sus fechas de publicación**

![adela-588b](https://cloud.githubusercontent.com/assets/2633527/10590148/cf3e9382-7674-11e5-8bd3-f27dd0f4f657.png)

**Comment by carlosmaya** [comment]
No aplica. Para la v3 desaparece el flujo de plan de apertura y se unifica con el inventario de datos
