### ISSUE TITLE
Quitar tour de ayudar

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/adela#968]
No incluir tour de ayuda para el taller, creo que es confuso si no se tiene la funcionalidad

¿Qué opinan @netosw @lolaiturbe ?

**Comment by netosw** [comment]
@carlosmaya @lolaiturbe creo que podemos dejarlo pero deshabilitar el botón, así van a poder que estamos desarrollando la funcionalidad pero no esta disponible todavía.
